// <auto-generated />
using System;
using Autenticacion.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autenticacion.Infraestructura.Migrations
{
    [DbContext(typeof(AutenticationDbContext))]
    [Migration("20200131222957_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Autenticacion")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles","dbo");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.Usuarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers","dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRoleClaim<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserClaim<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserLogin<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserToken<Guid>");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.RolesReclamaciones", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<Guid?>("RolesId");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasIndex("RolesId");

                    b.HasDiscriminator().HasValue("RolesReclamaciones");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosReclamaciones", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid?>("UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosReclamaciones","dbo");

                    b.HasDiscriminator().HasValue("UsuariosReclamaciones");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuarioLogin", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid?>("UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosLogin","dbo");

                    b.HasDiscriminator().HasValue("UsuarioLogin");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosRoles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<Guid?>("RolesId");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid?>("UsuariosId");

                    b.HasIndex("RolesId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosRoles","dbo");

                    b.HasDiscriminator().HasValue("UsuariosRoles");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosToken", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("CHAR(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<Guid>("UsuarioCreacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("UsuarioModificacion")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid?>("UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuariosToken","dbo");

                    b.HasDiscriminator().HasValue("UsuariosToken");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.RolesReclamaciones", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Roles", "Roles")
                        .WithMany("RoleReclamacion")
                        .HasForeignKey("RolesId");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosReclamaciones", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios", "Usuarios")
                        .WithMany("UsuariosReclamaciones")
                        .HasForeignKey("UsuariosId");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuarioLogin", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios", "Usuarios")
                        .WithMany("UsuarioLogin")
                        .HasForeignKey("UsuariosId");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosRoles", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Roles", "Roles")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolesId");

                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios", "Usuarios")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuariosId");
                });

            modelBuilder.Entity("Autenticacion.Dominio.Entidades.UsuariosToken", b =>
                {
                    b.HasOne("Autenticacion.Dominio.Entidades.Usuarios", "Usuarios")
                        .WithMany("UsuariosTokens")
                        .HasForeignKey("UsuariosId");
                });
#pragma warning restore 612, 618
        }
    }
}
